-- Incremental migration: multiple libraries ("catalogs") + category tags
-- Safe to run multiple times.

-- -----------------------
-- Libraries (multiple catalogs per user)
-- -----------------------
create table if not exists public.libraries (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references public.profiles (id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now(),
  unique (owner_id, name)
);

alter table public.libraries enable row level security;

drop policy if exists "libraries_select_owner" on public.libraries;
create policy "libraries_select_owner"
on public.libraries
for select
using (auth.uid() = owner_id);

drop policy if exists "libraries_insert_owner" on public.libraries;
create policy "libraries_insert_owner"
on public.libraries
for insert
with check (auth.uid() = owner_id);

drop policy if exists "libraries_update_owner" on public.libraries;
create policy "libraries_update_owner"
on public.libraries
for update
using (auth.uid() = owner_id)
with check (auth.uid() = owner_id);

drop policy if exists "libraries_delete_owner" on public.libraries;
create policy "libraries_delete_owner"
on public.libraries
for delete
using (auth.uid() = owner_id);

-- Add library_id to user_books (nullable first, then backfill, then NOT NULL).
alter table public.user_books
  add column if not exists library_id bigint;

do $$
begin
  -- Make sure the FK uses ON DELETE CASCADE (library_id becomes NOT NULL below).
  alter table public.user_books
    drop constraint if exists user_books_library_id_fkey;

  alter table public.user_books
    add constraint user_books_library_id_fkey
    foreign key (library_id) references public.libraries (id)
    on delete cascade;
end $$;

create index if not exists user_books_library_id_idx on public.user_books (library_id);

-- Create a default library for any existing owner that doesn't have one.
insert into public.libraries (owner_id, name)
select distinct ub.owner_id, 'Your catalog'
from public.user_books ub
where not exists (select 1 from public.libraries l where l.owner_id = ub.owner_id);

-- Backfill user_books.library_id to the first library per owner.
with first_lib as (
  select owner_id, min(id) as id
  from public.libraries
  group by owner_id
)
update public.user_books ub
set library_id = fl.id
from first_lib fl
where ub.library_id is null
  and ub.owner_id = fl.owner_id;

-- Make library_id required once backfilled.
do $$
begin
  if exists (
    select 1
    from information_schema.columns c
    where c.table_schema = 'public'
      and c.table_name = 'user_books'
      and c.column_name = 'library_id'
      and c.is_nullable = 'YES'
  ) then
    alter table public.user_books
      alter column library_id set not null;
  end if;
end $$;

-- -----------------------
-- Tag kinds (regular tags vs category tags)
-- -----------------------
alter table public.tags
  add column if not exists kind text;

update public.tags
set kind = 'tag'
where kind is null;

alter table public.tags
  alter column kind set not null;

do $$
begin
  if not exists (
    select 1
    from information_schema.table_constraints tc
    where tc.table_schema = 'public'
      and tc.table_name = 'tags'
      and tc.constraint_type = 'CHECK'
      and tc.constraint_name = 'tags_kind_check'
  ) then
    alter table public.tags
      add constraint tags_kind_check check (kind in ('tag', 'category'));
  end if;
end $$;

-- Expand uniqueness to allow the same name in different kinds.
alter table public.tags
  drop constraint if exists tags_owner_id_name_key;

do $$
begin
  if not exists (
    select 1
    from information_schema.table_constraints tc
    where tc.table_schema = 'public'
      and tc.table_name = 'tags'
      and tc.constraint_type = 'UNIQUE'
      and tc.constraint_name = 'tags_owner_id_name_kind_key'
  ) then
    alter table public.tags
      add constraint tags_owner_id_name_kind_key unique (owner_id, name, kind);
  end if;
end $$;

create index if not exists tags_owner_kind_idx on public.tags (owner_id, kind);
