-- Borrowing: per-profile defaults + per-book overrides + borrow requests.
-- Safe to run multiple times.

-- -----------------------
-- Profile defaults
-- -----------------------
alter table public.profiles
  add column if not exists borrowable_default boolean not null default false;

alter table public.profiles
  add column if not exists borrow_request_scope text not null default 'approved_followers';

do $$
begin
  if not exists (
    select 1
    from information_schema.table_constraints tc
    where tc.table_schema = 'public'
      and tc.table_name = 'profiles'
      and tc.constraint_type = 'CHECK'
      and tc.constraint_name = 'profiles_borrow_request_scope_check'
  ) then
    alter table public.profiles
      add constraint profiles_borrow_request_scope_check check (borrow_request_scope in ('anyone', 'approved_followers'));
  end if;
end $$;

-- -----------------------
-- Per-book overrides (null = inherit profile defaults)
-- -----------------------
alter table public.user_books
  add column if not exists borrowable_override boolean;

alter table public.user_books
  add column if not exists borrow_request_scope_override text;

do $$
begin
  if not exists (
    select 1
    from information_schema.table_constraints tc
    where tc.table_schema = 'public'
      and tc.table_name = 'user_books'
      and tc.constraint_type = 'CHECK'
      and tc.constraint_name = 'user_books_borrow_request_scope_override_check'
  ) then
    alter table public.user_books
      add constraint user_books_borrow_request_scope_override_check check (
        borrow_request_scope_override is null or borrow_request_scope_override in ('anyone', 'approved_followers')
      );
  end if;
end $$;

-- -----------------------
-- Borrow requests
-- -----------------------
create table if not exists public.borrow_requests (
  id bigint generated by default as identity primary key,
  user_book_id bigint not null references public.user_books (id) on delete cascade,
  owner_id uuid not null references public.profiles (id) on delete cascade,
  requester_id uuid not null references public.profiles (id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'cancelled')),
  message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (owner_id <> requester_id)
);

create index if not exists borrow_requests_owner_status_idx on public.borrow_requests (owner_id, status, created_at desc);
create index if not exists borrow_requests_requester_created_idx on public.borrow_requests (requester_id, created_at desc);
create index if not exists borrow_requests_user_book_id_idx on public.borrow_requests (user_book_id);

alter table public.borrow_requests enable row level security;

drop trigger if exists trg_borrow_requests_updated_at on public.borrow_requests;
create trigger trg_borrow_requests_updated_at
before update on public.borrow_requests
for each row
execute function public.set_updated_at();

-- -----------------------
-- Allow profile visibility when a borrow request exists (for requester/owner)
-- -----------------------
create or replace function public.can_view_profile(target uuid)
returns boolean
language sql
stable
as $$
  select
    (auth.uid() = target)
    or public.is_public_profile(target)
    or (auth.uid() is not null and public.is_approved_follower(auth.uid(), target))
    or public.has_public_books(target)
    or (
      auth.uid() is not null
      and exists (
        select 1
        from public.follows f
        where (f.follower_id = auth.uid() and f.followee_id = target)
           or (f.followee_id = auth.uid() and f.follower_id = target)
      )
    )
    or (
      auth.uid() is not null
      and exists (
        select 1
        from public.borrow_requests br
        where (br.requester_id = auth.uid() and br.owner_id = target)
           or (br.owner_id = auth.uid() and br.requester_id = target)
      )
    );
$$;

drop policy if exists "borrow_requests_select_owner_or_requester" on public.borrow_requests;
create policy "borrow_requests_select_owner_or_requester"
on public.borrow_requests
for select
using (auth.uid() = owner_id or auth.uid() = requester_id);

drop policy if exists "borrow_requests_insert_requester" on public.borrow_requests;
create policy "borrow_requests_insert_requester"
on public.borrow_requests
for insert
with check (
  auth.uid() = requester_id
  and status = 'pending'
  and exists (
    select 1
    from public.user_books ub
    join public.profiles p on p.id = ub.owner_id
    where ub.id = user_book_id
      and ub.owner_id = owner_id
      and public.can_view_user_book(ub)
      and (
        case
          when ub.borrowable_override is null then p.borrowable_default
          else ub.borrowable_override
        end
      )
      and (
        case
          when ub.borrow_request_scope_override is null then p.borrow_request_scope
          else ub.borrow_request_scope_override
        end = 'anyone'
        or public.is_approved_follower(auth.uid(), ub.owner_id)
      )
  )
);

drop policy if exists "borrow_requests_update_owner" on public.borrow_requests;
create policy "borrow_requests_update_owner"
on public.borrow_requests
for update
using (auth.uid() = owner_id)
with check (auth.uid() = owner_id);

drop policy if exists "borrow_requests_cancel_requester" on public.borrow_requests;
create policy "borrow_requests_cancel_requester"
on public.borrow_requests
for update
using (auth.uid() = requester_id)
with check (auth.uid() = requester_id and status = 'cancelled');

drop policy if exists "borrow_requests_delete_owner_or_requester" on public.borrow_requests;
create policy "borrow_requests_delete_owner_or_requester"
on public.borrow_requests
for delete
using (auth.uid() = owner_id or auth.uid() = requester_id);
