-- Borrow request messages (chat) + require initial message.
-- Safe to run multiple times.

create table if not exists public.borrow_request_messages (
  id bigint generated by default as identity primary key,
  borrow_request_id bigint not null references public.borrow_requests (id) on delete cascade,
  sender_id uuid not null references public.profiles (id) on delete cascade,
  message text not null,
  created_at timestamptz not null default now(),
  check (length(trim(message)) > 0)
);

create index if not exists borrow_request_messages_borrow_request_id_created_idx
  on public.borrow_request_messages (borrow_request_id, created_at asc);

alter table public.borrow_request_messages enable row level security;

drop policy if exists "borrow_request_messages_select_owner_or_requester" on public.borrow_request_messages;
create policy "borrow_request_messages_select_owner_or_requester"
on public.borrow_request_messages
for select
using (
  auth.uid() is not null
  and exists (
    select 1
    from public.borrow_requests br
    where br.id = borrow_request_id
      and (br.owner_id = auth.uid() or br.requester_id = auth.uid())
  )
);

drop policy if exists "borrow_request_messages_insert_owner_or_requester" on public.borrow_request_messages;
create policy "borrow_request_messages_insert_owner_or_requester"
on public.borrow_request_messages
for insert
with check (
  auth.uid() is not null
  and auth.uid() = sender_id
  and exists (
    select 1
    from public.borrow_requests br
    where br.id = borrow_request_id
      and (br.owner_id = auth.uid() or br.requester_id = auth.uid())
      and br.status in ('pending', 'approved')
  )
);

-- Keep borrow_requests.updated_at fresh when a message is sent (so inbox sorts correctly).
create or replace function public.touch_borrow_request_updated_at()
returns trigger
language plpgsql
security definer
as $$
begin
  update public.borrow_requests
  set updated_at = now()
  where id = new.borrow_request_id;
  return new;
end;
$$;

drop trigger if exists trg_borrow_request_messages_touch on public.borrow_request_messages;
create trigger trg_borrow_request_messages_touch
after insert on public.borrow_request_messages
for each row
execute function public.touch_borrow_request_updated_at();

-- Require initial message on borrow request insert (and disable "note" requests in the app).
drop policy if exists "borrow_requests_insert_requester" on public.borrow_requests;
create policy "borrow_requests_insert_requester"
on public.borrow_requests
for insert
with check (
  auth.uid() = requester_id
  and status = 'pending'
  and kind = 'borrow'
  and message is not null
  and length(trim(message)) > 0
  and exists (
    select 1
    from public.user_books ub
    join public.profiles p on p.id = ub.owner_id
    where ub.id = user_book_id
      and ub.owner_id = owner_id
      and public.can_view_user_book(ub)
      and (
        case
          when ub.borrowable_override is null then p.borrowable_default
          else ub.borrowable_override
        end
      )
      and (
        case
          when ub.borrow_request_scope_override is null then p.borrow_request_scope
          else ub.borrow_request_scope_override
        end = 'anyone'
        or public.is_approved_follower(auth.uid(), ub.owner_id)
      )
  )
);

