create table if not exists public.homepage_feature_slots (
  id bigint generated by default as identity primary key,
  surface text not null,
  slot_index integer not null,
  mode text not null default 'automatic',
  role text,
  entity_id uuid references public.entities(id) on delete set null,
  title_override text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint homepage_feature_slots_surface_check check (surface in ('explore_right_rail')),
  constraint homepage_feature_slots_slot_index_check check (slot_index between 1 and 3),
  constraint homepage_feature_slots_mode_check check (mode in ('automatic', 'pinned')),
  constraint homepage_feature_slots_role_check check (role is null or role in ('author', 'designer', 'publisher', 'performer')),
  constraint homepage_feature_slots_surface_slot_key unique (surface, slot_index)
);

create or replace function public.set_homepage_feature_slots_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_homepage_feature_slots_updated_at on public.homepage_feature_slots;
create trigger set_homepage_feature_slots_updated_at
before update on public.homepage_feature_slots
for each row
execute function public.set_homepage_feature_slots_updated_at();
